FROM python:3.8-slim
 
WORKDIR /work
 
COPY . /work

RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 4001

CMD ["python", "main.py"]